# Generated by Django 2.1.4 on 2018-12-16 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_of_measurement', models.DateTimeField()),
            ],
            options={
                'db_table': 'measurements',
            },
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('Name', models.CharField(max_length=200)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='BigParticlesMeasurements',
            fields=[
                ('Measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Station_controlls.Measurements')),
                ('Value', models.FloatField()),
                ('Unit', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'big_particle_measurements',
            },
        ),
        migrations.CreateModel(
            name='HumidityMeasurements',
            fields=[
                ('Measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Station_controlls.Measurements')),
                ('Value', models.FloatField()),
            ],
            options={
                'db_table': 'humidity_measurements',
            },
        ),
        migrations.CreateModel(
            name='PressureMeasurements',
            fields=[
                ('Measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Station_controlls.Measurements')),
                ('Value', models.FloatField()),
                ('Unit', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pressure_measurements',
            },
        ),
        migrations.CreateModel(
            name='SmallParticlesMeasurements',
            fields=[
                ('Measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Station_controlls.Measurements')),
                ('Value', models.FloatField()),
                ('Unit', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'small_particle_measurements',
            },
        ),
        migrations.CreateModel(
            name='TemperatureMeasurements',
            fields=[
                ('Measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Station_controlls.Measurements')),
                ('Value', models.FloatField()),
                ('Unit', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'temperature_measurements',
            },
        ),
        migrations.AddField(
            model_name='measurements',
            name='Station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Station_controlls.Stations'),
        ),
    ]
