# Generated by Django 2.1.4 on 2018-12-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station_controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMeasurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Station', models.CharField(max_length=200)),
                ('Temperature', models.FloatField()),
                ('TemperatureUnit', models.CharField(max_length=20)),
                ('Pressure', models.FloatField()),
                ('PressureUnit', models.CharField(max_length=20)),
                ('Humidity_percentage', models.FloatField()),
                ('PM25', models.FloatField()),
                ('PM25_unit', models.CharField(max_length=20)),
                ('PM10', models.FloatField()),
                ('PM10_unit', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'all_measurements',
                'managed': False,
            },
        ),
    ]
